services:
    _defaults:
        autoconfigure: true

    zoglo_row_wizard.listener.add_assets:
        class: Zoglo\RowWizardBundle\EventListener\BackendAssetsListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@assets.packages'
