services:
    _defaults:
        autoconfigure: true

    zoglo_simple_column_wizard.listener.add_assets:
        class: Zoglo\SimpleColumnWizardBundle\EventListener\AddAssetsListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@assets.packages'
